### ISSUE TITLE
Delete dataset bottom in UI 

### ISSUE THREAD

**Issue by weixuanfu** [EpistasisLab/Aliro#197]
For now, users cannot delete the dataset or re-upload it (see the screenshot below) if the dataset has been uploaded to PennAI and also cannot change the metafeatures (categorical features or ordinal features) even if users found something wrong after uploading. 

I suggest that we should have edit metafeatures bottom and delate dataset bottom in UI. 

![image](https://user-images.githubusercontent.com/21084970/57230854-46f37680-6fe7-11e9-8faa-6f7ee7715d30.png)

**Comment by HyunjunA** [comment]
I propose the following idea in relation to the image below. The screenshot I shared displays a delete button for the card.

![Image](https://github.com/EpistasisLab/Aliro/assets/39776968/02bf8ce9-b19b-41ce-b00f-6bcbcd3ef73d)

**Comment by HyunjunA** [comment]
Jay suggested an idea on the delete button " it may be better to move that delete button so it's not next to the AI button, user may click 'delete' accidentally."

**Comment by jay-m-dev** [comment]
deleting the dataset entails removing the dataset, along with all related experiments and files attached to the dataset. We'll need a solution that will delete all these interdependent files and documents.

**Comment by jay-m-dev** [comment]
Tasks to be completed for dataset deletion:
- [ ] Add delete icon on GUI (@HyunjunA)
- [ ] Delete dataset from datasets collection
- [ ] Delete linked experiments
- [ ] Delete GridFS files
- [ ] Delete chats and chatlogs
- [ ] Delete linked code executions
  - [ ] Delete generated files from code executions

**Comment by jay-m-dev** [comment]
All tasks to delete in the backend are ready and merged on PR #610.  The last step is to implement the frontend.
@HyunjunA, please add the icon and please test that a deleted dataset can be re-uploaded and experiments can be run after re-uploading.
