### ISSUE TITLE
Feature importance plot issue?

### ISSUE THREAD

**Issue by wherrylab** [EpistasisLab/Aliro#260]
I am using pennAI0.13 as the latest version had rendering issue with multiple classes as in #257 .

The Feature importance plot i have for one of my experiments is blank when the accuracy is high(>90%),is this usual or some bug?

![image](https://user-images.githubusercontent.com/25934186/80410373-79e9e680-8898-11ea-9cae-8376c23e709f.png)

**Comment by weixuanfu** [comment]
This blank feature importance is abnormal and it might be a bug. Could you please provide a small dataset for allowing us to reproduce this issue? The dataset could be shared via email (please check the [link](https://github.com/weixuanfu) for my email info) so that we can keep it confidential.

**Comment by weixuanfu** [comment]
I tested SVC with c=0.5,gamma=0.5,kernel=poly,degree=2,coef0=100,tol=0.001 (from email communication) with some datasets from pmlb. SVC can finish in a few small datasets but cannot be finished in 5 mins with datasets with more than ~ 1000 rows. For finished SVC runs, the issue in importance score plot was not reproduced. I think we still need your dataset for reproducing this issue.
