### ISSUE TITLE
Incomparability issue with numpy 1.20.0

### ISSUE THREAD

**Issue by weixuanfu** [EpistasisLab/Aliro#311]
After comparing the CI builds passed last week with ones failed this week, I found that `numpy` was updated from 1.19 to 1.20 on Jan 30, 2021. I think it is the reason of failed CI builds. I pushed this commit 945fe3c459b578e9c9540209f088e846171c52c6 to `coveralls` branch to check if this can fix CI build.

**Comment by weixuanfu** [comment]
GitHub Action build passed after adding this commit.

**Comment by jay-m-dev** [comment]
I have confirmed that upgrading to numpy 1.20 causes errors. Version 1.19.5 is the latest version the currently works. See related (issue #481)[https://github.com/EpistasisLab/Aliro/issues/481].
 Numpy will be updated further than 1.19.5 only when absolutely necessary to upgrade.
