### ISSUE TITLE
Extend COMPOSE_HTTP_TIMEOUT during installation

### ISSUE THREAD

**Issue by matthewwritter** [EpistasisLab/Aliro#346]
When running `docker-compose up` for the very first time (5yo laptop, decent wifi, Ubuntu 18.04.6), I got this error:
```
ERROR: for pennai-017_lab_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for lab  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

I ran `set COMPOSE_HTTP_TIMEOUT=120` and then successfully ran `docker-compose up --force-reload`. I'd initially tried adding `--verbose` not realizing that it was not a docker-compose parameter.

Anyway, I'm a medium sophistication+motivation user, and I imagine many others would not have persisted through an immediate error on startup, so it seems worth fixing.

**Comment by jay-m-dev** [comment]
I've only seen this issue happen on low-power devices such as the Raspberry Pi 400. 

I have set DOCKER_CLIENT_TIMEOUT=120 and COMPOSE_HTTP_TIMEOUT=120 in common.env.
