### ISSUE TITLE
AI button on AliroEd always loading

### ISSUE THREAD

**Issue by miguelehernandez** [EpistasisLab/Aliro#490]
After running AliroEd in the RPI 400 the AI button stays in the loading state. 
This is in the latest released version 0.19

**Comment by jay-m-dev** [comment]
Updated the configuration to RECOMMENDER=random and the AI button now loads and works.
On the RPi 400 it will take 1 to 2 minutes to finish loading due to limited hardware resources.

**Comment by jay-m-dev** [comment]
The AI button has been confirmed working.
