### ISSUE TITLE
Add analytics to the aliro.ai website

### ISSUE THREAD

**Issue by jay-m-dev** [EpistasisLab/Aliro#501]
- [x] Need Google Analytics account
- [x] Set up Google Analytics

**Comment by jay-m-dev** [comment]
The account is now set up. We have two properties, one for aliro and one for aliroed.

**Comment by miguelehernandez** [comment]
How can we verify this? For obvioous tasks I do not mind the same person closing the issue, but for features like this, it is better to have peer-review and signoff on the issue, can this be implemented in the git issue workflow process?
