### ISSUE TITLE
Docs for GPT

### ISSUE THREAD

**Issue by jay-m-dev** [EpistasisLab/Aliro#592]
We need to update the documentation to reflect the newly added GPT chat and features.

**Comment by HyunjunA** [comment]
The content below, written in Markdown format, provides instructions on how to use the ChatGPT component. It is designed to be added to the user guide immediately after the section titled "Downloading and Using Models."

### Working with ChatGPT component

This document explains how to interact with the ChatGPT component. The guide covers the following topics:

1. Where to get your OpenAI API key
2. How to connect to OpenAI using your API key
3. How to use the ChatGPT (Expert)

---

#### 1. Where to Get Your OpenAI API Key

Before you can start using the ChatGPT component, you'll need an API key from OpenAI. To get one:

- Visit the [OpenAI website](https://openai.com/)
- Create an account or log in if you already have one
- Navigate to the API section and generate your API key

---

#### 2. How to Connect to OpenAI Using Your API Key

Once you have your API key, you can easily connect to OpenAI. The image below illustrates the window that appears when a user clicks on the "Expert" button.

![Window After Clicking Expert Button](URL-to-your-image)

After successfully connecting to OpenAI using your API key, you will see a popup window that says, "Connection to OpenAI is established," and the "Expert" button will turn blue.

#### 3. How to Use ChatGPT (Expert)

After clicking on the "Expert" button, a chat interface will appear. Refer to the image below for a visual overview.

![ChatGPT Expert Chatbox](URL-to-your-image)

##### Settings

At the top of the chat interface, you'll find the "Settings" tab and a "+ New Chat" button. Within "Settings," you can adjust the model, temperature, and define prompt engineering.

##### Renaming a Chat Tab

To rename the first chat tab to "EDA":

1. Double-click the tab to enable editing.
2. Enter the new name.
3. Hover over the pencil emoji, which will then change to a checkmark.
4. Click the checkmark to save the new name.

##### Creating a New Chat Tab

To create a new chat tab:

1. Click the "+ New Chat" button.
2. Name the new chat tab using the same process outlined above.

##### Removing Chat Tabs

To remove a chat tab, click on the trash bin emoji associated with that tab.

##### Code Generation and Editing

To request Python code from ChatGPT, you can ask, for example: "Please write Python code to generate 10 random numbers and print them."

To edit the generated code:

1. Double-click the code box.
2. Make your changes.
3. To save, press the ESC key or click the "Run" button.

##### Installing New Packages

If you need to install new packages to run the given code, a "Install and Run" button will appear. Clicking this will install the necessary packages and execute the code.

**Comment by jay-m-dev** [comment]
This documentation was added and published in the [user guide](https://epistasislab.github.io/Aliro/userguide.html#working-with-chatgpt-component).
