### ISSUE TITLE
Python Execution Error on Aliro

### ISSUE THREAD

**Issue by HyunjunA** [EpistasisLab/Aliro#595]
When attempting to run Python code on Aliro, the following error occurs

<img width="839" alt="Screen Shot 2023-08-14 at 1 56 31 PM" src="https://github.com/EpistasisLab/Aliro/assets/39776968/03c4d8e9-1af2-43da-b024-d4ec091771a0">

**Comment by jay-m-dev** [comment]
This issue is fixed on commit https://github.com/EpistasisLab/Aliro/commit/a96a447237d142c8606c7757ab1b9b290b1f5aee.

**Comment by miguelehernandez** [comment]
Can Jun verify this was fixed to his satisfaction?

**Comment by HyunjunA** [comment]
![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/0e2b6724-427a-4bcf-8f38-d33bc2aa80cb/7aaa78ca-7a46-4310-8fcd-ce8b8932cd1a/Untitled.png)

When I asked a simple question, such as 'print hello,' I encountered an error message that I posted above. I've modified the code as shown below, and it resolved the error. However, I'm not sure if this change will lead to other potential issues.


  if (req.body.packages === null && req.body.command !== "freeze") {
    return res.status(400).json({ message: "No packages provided" });
  }

**Comment by jay-m-dev** [comment]
@HyunjunA while testing the `/install` endpoint I found another enhancement that's needed for this and the code run endpoint. Since this issue is for a different reason and for a different endpoint. I've opened issue #597. I'll include the fix for this **length** undefined error in the fix to #597.
