### ISSUE TITLE
DataCard is deleted before the dataset.

### ISSUE THREAD

**Issue by jay-m-dev** [EpistasisLab/Aliro#614]
The datacard for a dataset should be deleted only until the dataset and all dependencies are deleted from the DB. The DELETE `api/v1/datasets/:id` returns HTTP code 200 when the dataset is deleted successfully. The datacard should remain on the GUI until code 200 is received.

Currently the datacard is deleted first and then the API call is sent.

# Steps to recreate:

1. Upload a dataset
2. Enable the AI button (so that multiple experiments are triggered)
3. Click the **delete** icon

After hitting the **delete** icon, the datacard disappears, but the dataset is not deleted (since there are running experiments).

# Expected behavior:
The datacard should not disappear and one of the following options should occur:
1. Alert the user that the dataset cannot be deleted, or
2. disable the **delete** icon while experiments are running.

**Comment by HyunjunA** [comment]
### 🛠 Code Update:
I've made changes to the code. Now, when the AI is active, clicking on the datacard's delete icon will trigger the displayed alert.
![image](https://github.com/EpistasisLab/Aliro/assets/39776968/14e63666-2896-41ea-a175-04a2ad048977)

### ⚠️ Error Issue:
However, after deleting a datacard, a 500 error, as described below, is displayed as Jay explained. I am currently investigating potential causes of the states in React.js.
![image](https://github.com/EpistasisLab/Aliro/assets/39776968/5a37b994-dcda-4ef4-a4f4-35182972b794)

**Comment by jay-m-dev** [comment]
I was able to recreate this (even after getting the "Cannot delete dataset" alert in PR #621. See notes there too.
I'm going to further revise the `DELETE` API endpoint to also check the value of the **ai** field. If the value is **_on_** or **_requested_**, then the `DELETE` endpoint should not proceed to delete anything and return HTTP code 409.
