### ISSUE TITLE
PennAI not working/freezing in IE

### ISSUE THREAD

**Issue by Coder-Sharon** [EpistasisLab/Aliro#85]
This issue is likely related to the Webpack/Babel configuration. The client-side code relies on future features of JavaScript which are transpiled by Babel as part of the webpack build process to JavaScript that will be supported by most browsers.

I believe PennAI was working in IE before I made some configuration changes to webpack and babel, but I don't know for sure. These changes can be seen in `lab/.babelrc`, `lab/package.json`, and `lab/webpack.config.js` in this commit: https://github.com/EpistasisLab/pennai/commit/603eaa003874473adb3adb0a4d22c6a97805c045

I followed this guide to make updates to the configuration: https://www.robinwieruch.de/minimal-react-webpack-babel-setup/

While following the guide, I removed the babel-polyfill library that was being used before. It might be possible that this library was allowing the app to work in IE: https://babeljs.io/docs/en/babel-polyfill.html

**Comment by jay-m-dev** [comment]
IE was retired as of June 15, 2022: https://www.microsoft.com/en-us/download/internet-explorer.aspx
